# app/core/localization.py

TRANSLATIONS = {
    "en": {
        "dashboard": "Dashboard",
        "production_orders": "Production Orders",
        "bakery_pastry": "Bakery/Pastry",
        "thawing": "Thawing",
        "cutting": "Cutting",
        "butchery": "Butchery",
        "marination": "Marination",
        "hot_kitchen": "Hot Kitchen",
        "cold_kitchen": "Cold Kitchen",
        "reports": "Reports",
        "settings": "Settings",
        "logout": "Logout",
        "Subscriptions": "Subscriptions",
        "New Subscription": "New Subscription",
        "My Subscriptions": "My Subscriptions",
        "Active": "Active",
        "Paused": "Paused",
        "Cancelled": "Cancelled",
        "Pause": "Pause",
        "Resume": "Resume",
        "Generate Due Orders Now": "Generate Due Orders Now",
        "Next Due": "Next Due",
        "Payroll": "Payroll",
        "Leave": "Leave",
        "Shifts": "Shifts",
    },
    "ar": {
        "dashboard": "لوحة التحكم",
        "production_orders": "أوامر الإنتاج",
        "bakery_pastry": "المخبوزات والحلويات",
        "thawing": "إذابة التجميد",
        "cutting": "التقطيع",
        "butchery": "الجزارة",
        "marination": "التتبيل",
        "hot_kitchen": "المطبخ الساخن",
        "cold_kitchen": "المطبخ البارد",
        "reports": "التقارير",
        "settings": "الإعدادات",
        "logout": "تسجيل الخروج",
        "Subscriptions": "الاشتراكات",
        "New Subscription": "اشتراك جديد",
        "My Subscriptions": "اشتراكاتي",
        "Active": "نشط",
        "Paused": "متوقف مؤقتاً",
        "Cancelled": "ملغى",
        "Pause": "إيقاف مؤقت",
        "Resume": "استئناف",
        "Generate Due Orders Now": "إنشاء الطلبات المستحقة الآن",
        "Next Due": "الاستحقاق التالي",
        "Payroll": "الرواتب",
        "Leave": "الإجازات",
        "Shifts": "الورديات",
    }
}


def t(key: str, lang: str = "en") -> str:
    return TRANSLATIONS.get(lang, TRANSLATIONS["en"]).get(key, key)